
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5 
  port: 5432

development:
  <<: *default
  database: my_new_app_development
  username: postgres
  password: postgres
  host: 127.0.0.1


test:
  <<: *default
  database: my_new_app_test
  username: postgres
  password: postgres
  host: 127.0.0.1
